### ISSUE TITLE
bug: site not opening

### ISSUE THREAD

**Issue by priyankarpal** [The-Lively-Developers-Community/introductions#12]
PLease look into this problem. The website not opening.

![Screenshot from 2023-04-10 23-14-30](https://user-images.githubusercontent.com/88102392/230960936-7191cb38-1657-47b7-8139-a6c9672cc1dc.png)

**Comment by KendallDoesCoding** [comment]
> PLease look into this problem. The website not opening.
> 
> ![Screenshot from 2023-04-10 23-14-30](https://user-images.githubusercontent.com/88102392/230960936-7191cb38-1657-47b7-8139-a6c9672cc1dc.png)

We are aware of this issue, we want to README.md to go in the site (which we can do) but there is some issue with the domain, which I'm working on fixing.

**Comment by KendallDoesCoding** [comment]
Fixed.... Due to DNS setting issues with Namecheap, I made http://introductions.thelivelydevelopers.me/ redirect to the GitHub pages. There are 2 domains that can take you to the website.
