### ISSUE TITLE
Branch to Create a Markdown table and see how GitHub Pages renders the website.

### ISSUE THREAD

**Issue by KendallDoesCoding** [The-Lively-Developers-Community/introductions#40]
> > Not sure if this is 100% needed. Would be better if we could use a [Markdown table](https://www.markdownguide.org/extended-syntax/).
> 
> Can you make a branch where you add a markdown table and we see how github pages deploys the website? @Panquesito7

It'd be best to create an issue so that everyone can discuss about it and work on it as well. 🙂

_Originally posted by @Panquesito7 in https://github.com/The-Lively-Developers-Community/introductions/issues/35#issuecomment-1541317670_

**Comment by gekkowrld** [comment]
I tried gh pages with `hacker theme` and it was great, but not sure how it will look with other themes or when it is plain

**Comment by Panquesito7** [comment]
I'll see if I can do it and will let you know how does it look. 🙂
