### ISSUE TITLE
[DOCS] Add contributing guidelines

### ISSUE THREAD

**Issue by Panquesito7** [The-Lively-Developers-Community/introductions#43]
### Description

After merging #42, a proper contributing guidelines file will be needed for easier addition of the introductions.
We need to specify how to add your name to the list properly, as well as other minor stuff such as using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and following our Code of Conduct.

**Comment by Panquesito7** [comment]
Working on it.

**Comment by KendallDoesCoding** [comment]
> Working on it.

I created a branch contributing-guidelines to the repo and added something, but it needs adjustments see if you can work with that. Otherwise, it's ok if you start from scratch too.

**Comment by Panquesito7** [comment]
Created a commit now. Feel free to create the PR. 🙂

**Comment by KendallDoesCoding** [comment]
> Created a commit now. Feel free to create the PR. 🙂

Everything looks good, only one thing that I commented in the CONTRIBUTING.md file, latest commit.

**Comment by Panquesito7** [comment]
> > Created a commit now. Feel free to create the PR. 🙂
> 
> Everything looks good, only one thing that I commented in the CONTRIBUTING.md file, latest commit.

Should be fixed now. 👍

**Comment by KendallDoesCoding** [comment]
@Panquesito7 - can you please make the PR.

**Comment by Panquesito7** [comment]
Created! #46.

**Comment by KendallDoesCoding** [comment]
fixed in #46
